@startuml
!pragma layout smetana
left to right direction
actor "Gamer Face User" as gfu
rectangle GamerFace {
  usecase "Sign Up" as UC1
  usecase "Update Profile" as UC2
  usecase "Delete Profile" as UC3
  usecase "Search Profile" as UC4
}
gfu --> UC1
gfu --> UC2
gfu --> UC3
gfu --> UC4
@enduml